spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/autohub_vehicles
    username: vehiclesadmin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

