spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/autohub_vehicles
    username: vehiclesadmin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

aws:
  region: us-east-1 # Ou sua região default
  localstack:
    endpoint: http://localhost:4566 # Endpoint padrão do LocalStack
  credentials:
    accessKey: test # Credenciais dummy para LocalStack
    secretKey: test

sqs:
  queue:
    vehicles-sale-created: VehiclesApi_SaleCreated_Queue-local

sns:
  topic:
    main-event-bus-arn: arn:aws:sns:us-east-1:000000000000:AutoHubBusinessEventsTopic-local
